function A_next = A_iter(A,Gamma_d,s_d,s_l,mu_y,mu_l,tau_l,tau_k,sigma,eta,gamma_L,gamma_K,gamma_j)
    % Gamma_d = (1./(1+ex));
    X = -gamma_j / ( sigma/(sigma-1)-gamma_j );
    A_next =( (s_d(1:end-1)...
        *sum( ( [A;1].^(-1/gamma_j).*mu_y.*(mu_l.*tau_l.*(s_l.^(1/(eta+1)))).^(gamma_L/gamma_j)...
        .*tau_k.^(gamma_K/gamma_j).*Gamma_d.^((gamma_j-1)/gamma_j)).^X ) ).^(1/X)...
    ./( mu_y(1:end-1).*(mu_l(1:end-1).*tau_l(1:end-1).*(s_l(1:end-1).^(1/(eta+1)))).^(gamma_L/gamma_j)...
    .*(tau_k(1:end-1)).^(gamma_K/gamma_j).*Gamma_d(1:end-1).^((gamma_j-1)/gamma_j))).^(-gamma_j);
end
% 1/(1+ex) = Gamma

% s_y_check=( ( [A;1].^(-1/gamma_j).*mu_y.*(mu_l.*tau_l).^(gamma_L/gamma_j).*tau_k.^(gamma_K/gamma_j)...
%         .*s_l.^(gamma_L/(gamma_j*(eta+1))).*(1+ex).^((1-gamma_j)/gamma_j) ).^X )./...
%  sum( ( [A;1].^(-1/gamma_j).*mu_y.*(mu_l.*tau_l).^(gamma_L/gamma_j).*tau_k.^(gamma_K/gamma_j)...
%         .*s_l.^(gamma_L/(gamma_j*(eta+1))).*(1+ex).^((1-gamma_j)/gamma_j) ).^X );