function x_updated = model_damped_update(...
    x_next,x_current,total_firm,dmp,dmp_small,context)
% Apply one fixed-point damping step without implicit expansion.

if ~isvector(x_next) || ~isvector(x_current)
    error('model_damped_update:NonvectorIterate',...
        '%s received x_next %s and x_current %s.',...
        context,mat2str(size(x_next)),mat2str(size(x_current)));
end
if ~isscalar(dmp) || ~isscalar(dmp_small) ...
        || ~isfinite(dmp) || ~isfinite(dmp_small)
    error('model_damped_update:InvalidDamping',...
        '%s received damping sizes %s and %s.',...
        context,mat2str(size(dmp)),mat2str(size(dmp_small)));
end

x_next = x_next(:);
x_current = x_current(:);
if numel(x_next)~=numel(x_current)
    error('model_damped_update:IterateSizeMismatch',...
        '%s received iterates with %d and %d elements.',...
        context,numel(x_next),numel(x_current));
end
if ~isscalar(total_firm) || total_firm<1 ...
        || total_firm~=floor(total_firm) || total_firm>=numel(x_next)
    error('model_damped_update:InvalidFirmCount',...
        '%s received total_firm=%s for a %d-element state.',...
        context,mat2str(total_firm),numel(x_next));
end

x_updated = x_current;
x_updated(1:total_firm) = dmp_small*x_next(1:total_firm)...
    +(1-dmp_small)*x_current(1:total_firm);
x_updated(total_firm+1:end) = dmp*x_next(total_firm+1:end)...
    +(1-dmp)*x_current(total_firm+1:end);
end
